# Generated by Django 4.0.4 on 2023-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name': 'Мерч', 'verbose_name_plural': 'Мерч'},
        ),
        migrations.AlterModelOptions(
            name='releases',
            options={'verbose_name': 'Релиз', 'verbose_name_plural': 'Релизы'},
        ),
        migrations.AlterModelOptions(
            name='ticketsshop',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='releases',
            name='release_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketsshop',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
