# Generated by Django 4.0.4 on 2023-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_merch_options_alter_releases_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsshop',
            name='date',
            field=models.DateField(verbose_name='Дата концерта'),
        ),
    ]
