# Generated by Django 4.0.4 on 2023-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_releases_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='list',
        ),
        migrations.AddField(
            model_name='releases',
            name='apple_music',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='vkontakte',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releases',
            name='youtube_music',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releases',
            name='image',
            field=models.ImageField(upload_to='releases', verbose_name='Изображение'),
        ),
    ]
