# Generated by Django 4.0.4 on 2023-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_releases_list_releases_apple_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='color',
            field=models.CharField(choices=[(None, 'Выберите цвет'), ('wh', 'White'), ('bl', 'Black'), ('gr', 'Grey'), ('vl', 'Violet')], max_length=128, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size',
            field=models.CharField(choices=[(None, 'Выберите размер'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=128, verbose_name='Размер'),
        ),
    ]
